In [50]:
import numpy as np

P = np.array([
    [.2, .3, .5],
    [.4, .2, .4],
    [.5, .3, .2]    
])

A0 = np.array([1, 0, 0])


In [51]:
# 1. Матрица переходных состояний за k шагов
def p_on_step_k(p, k):
    res_p = p.copy()
    for _ in range(k-1):
        res_p = res_p @ p
    return res_p


In [52]:
p_on_step_k(P, 1)

array([[0.2, 0.3, 0.5],
       [0.4, 0.2, 0.4],
       [0.5, 0.3, 0.2]])

In [10]:
# 2. Вероятность состояний спустя k шагов
def a_on_step_k(a, p, k):
    return a @ p_on_step_k(p, k)

In [14]:
a_on_step_k(A0, P, 1)

array([0.2, 0.3, 0.5])

In [53]:
# 3. Вероятность первого перехода за k шагов

def first_on_step_k(p, k):
    if k == 0:
        return 
    if k == 1:
        return p
    
    m = len(p)
    n = len(p[0])
    
    res = np.zeros((m, n))
    
    pre = first_on_step_k(p, k-1)
    for i in range(m):
        for j in range(n):
            row = p[i].copy()
            row[j] = 0
            col = pre[:,j].copy()
            col[j] = 0
            res[i, j] = np.dot(row, col)
    
    return res    
    

In [55]:
first_on_step_k(P, 2)

array([[0.37, 0.21, 0.22],
       [0.28, 0.24, 0.28],
       [0.22, 0.21, 0.37]])

In [1]:
# 3.1 Вероятность перехода не позднее чем за k шагов
no_later_then_k(p, k):
    res = np.zeros((len(p), len(p[0])))
    for i in range(1, k):
        res = res + first_on_step_k(p, i)
    return res

SyntaxError: invalid syntax (<ipython-input-1-055c50df23b2>, line 2)

In [ ]:
3.2

In [27]:
a = np.zeros((3,4))
# help(np.zeros)
a[2,1] = 3

4

In [32]:
t = np.arange(9).reshape((3,3))
t[:, [0]]
    [.2, .3, .5],
    [.4, .2, .4],
    [.5, .3, .2] 

array([[0],
       [3],
       [6]])

array([[0. , 0.3, 0.5],
       [0.4, 0. , 0.4],
       [0.5, 0.3, 0. ]])