## Списки и массивы

## Задания для самостоятельной работы
### Заваруев И.
### ПИ19-1в
Создать матрицу из n строк и m столбцов (n=4, m=3) явно указав ее элементы в виде списка списков. Используя numpy, создать двумерный массив для хранения этой же матрицы

In [15]:
# Размерность матриц 
n, m = 4, 3

#--------------------------------------
# Создание списка списков
from random import randint

arr = [[randint(0, 10) for _ in range(n)] for _ in range(m)]

print('Список списков:')
for line in arr:
    print(line)
    
#--------------------------------------
# Создание NumPy массива
import numpy as np

np_arr = np.array(arr)

print('NymPy массив:')
print(np_arr)

Список списков:
[2, 4, 6, 3]
[5, 6, 1, 3]
[8, 2, 6, 3]
NymPy массив:
[[2 4 6 3]
 [5 6 1 3]
 [8 2 6 3]]


Вычислить количество строк, содержащих нули


In [17]:
def nuls(arr):
    return sum([0 in line for line in arr])
print(nuls(arr))
%timeit nuls(arr)

0
1.45 µs ± 21.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [16]:
def nuls_np(arr):
    return np.count_nonzero([line==0 for line in arr])
print(nuls_np(np_arr))
%timeit nuls_np(np_arr)

0
14.3 µs ± 98.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Проверить, есть ли в исходной матрице одинаковые строки

In [18]:
def equals(arr):
    res = 0
    for i in range(len(arr)):
        for j in range(i+1, len(arr)):
            if arr[i] == arr[j]:
                res += 1
    return res        
print(equals(arr))
%timeit equals(arr)

0
3.57 µs ± 26.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
def equals_np(arr):
    res = 0
    for i in range(len(arr)):
        for j in range(i+1, len(arr)):
            if np.array_equal(arr[i],arr[j]):
                res += 1
    return res        
print(equals_np(np_arr))
%timeit equals_np(np_arr)

0
28.7 µs ± 447 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Найти произведение 2 матриц. Для этого создайте еще одну матрицу подходящего размера.

In [20]:
# Новые матрицы для умножения
arr1 = [[randint(0, 10) for _ in range(m)] for _ in range(n)]

print('Список списков:')
for line in arr1:
    print(line)
    
#--------------------------------------

np_arr1 = np.array(arr1)

print('NymPy массив:')
print(np_arr1)

Список списков:
[9, 0, 3]
[10, 8, 2]
[9, 4, 8]
[7, 5, 0]
NymPy массив:
[[ 9  0  3]
 [10  8  2]
 [ 9  4  8]
 [ 7  5  0]]


In [21]:
# Умножение списков списков
def get_el(a, b, i, j, y):
#     print(f'i: {i}, j: {j}')
    res = 0
    for k in range(y):
#         print(f'a[{i}][{k}] * b[{k}][{j}] ')
        res += a[i][k] * b[k][j]
    return res

def mul(a, b):
    x, y = len(a), len(b)
#     print(x, y)
    return [[get_el(a,b,i,j,y)  for j in range(x)] for i in range(x)]
    
    
print(mul(arr,arr1))
%timeit mul(arr, arr1)

[[133, 71, 62], [135, 67, 35], [167, 55, 76]]
23.1 µs ± 1.29 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [22]:
# Умножение NumPy массивов
def mul_np(arr1, arr2):
    return arr1.dot(arr2)
print(mul_np(np_arr, np_arr1))
%timeit mul_np(np_arr, np_arr1)

[[133  71  62]
 [135  67  35]
 [167  55  76]]
2.88 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
